---
title: "Week8"
output: html_document
date: "2025-10-10"
---



```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, eval = FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
#klippy::klippy(color = 'darkred')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>



```{r, EVAL = FALSE}
library(RSiena)

mynet1 <- sienaDependent(array(c(s501, s502, s503), dim=c(50, 50, 3)))
mybeh <- sienaDependent(s50a, type="behavior")
smoke <- s50s
smoke <- varCovar(s50s)

drinking <- varCovar(s50a)

mydata <- sienaDataCreate(mynet1, mybeh, drinking, smoke)

```


```{r}
print01Report(mydata)
```

```{r, EVAL = FALSE}
myeff <- getEffects(mydata)
myeff <- includeEffects(myeff, unequalX, name = "mynet1", interaction1 = "smoke")

myeff <- includeEffects(myeff, unequalX, name = "mynet1", interaction1 = "drinking")
```
```{r}
algo <- sienaAlgorithmCreate()
```

```{r, EVAL = FALSE}
ans <- siena07(algo, data=mydata, effects = myeff, returnDeps = TRUE)
ans


```

```{r, EVAL = FALSE}
gofo0 <- sienaGOF(ans, OutdegreeDistribution, verbose = FALSE, join = TRUE, varName = "mynet1")


gofo0 <- sienaGOF(ans, OutdegreeDistribution, verbose = FALSE, join = TRUE, varName = "mynet1")

```





